  
image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8081

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
  - init: sudo apt-get install openjdk-8-jdk
    command: sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  - command: export JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
  - command: java -version
